/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Preference.java
 *
 * Created on 23-May-2009, 17:18:59
 */

package intranetchat.display;

import intranetchat.saving.SavedValues;

/**
 *
 * @author Philip
 */
public class Preference extends javax.swing.JDialog {
    SavedValues values;
    /** Creates new form Preference */
    public Preference(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        values = SavedValues.getInstance();
        this.setLocation(values.x+50, values.y+50);
        this.setVisible(true);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
