/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FileUpload.java
 *
 * Created on 30-May-2009, 12:02:26
 */

package intranetchat.display;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Philip
 */
public class FileUpload extends javax.swing.JDialog {


    /** Creates new form FileUpload */
    public FileUpload(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        JFileChooser chooser  = new JFileChooser();
        int returnVal = chooser.showOpenDialog(null);
        if(!(returnVal == JFileChooser.APPROVE_OPTION)) {
            this.dispose();
        }
        File f = chooser.getSelectedFile();
        
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 4, 4);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
