/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FileUpload.java
 *
 * Created on 30-May-2009, 12:02:26
 */

package intranetchat.display;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

import javax.swing.JFileChooser;

/**
 *
 * @author Philip
 */
public class FileUpload extends javax.swing.JDialog {
    byte[] trans;

    /** Creates new form FileUpload */
    public FileUpload(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        //Starts the JFileChooser so a file can be selected
        JFileChooser chooser  = new JFileChooser();
        int returnVal = chooser.showOpenDialog(null);
        if(!(returnVal == JFileChooser.APPROVE_OPTION)) {
            this.dispose();
        }

        File f = chooser.getSelectedFile();
        try{
            trans = getFileBytes(f);
        }catch(IOException ex){

        }

        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 4, 4);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    /**
     * This file will take the file and convert it into a byte[]
     * @param f the file that is to be converted into a byte[]
     * @return the byte[] of the file
     * @throws java.io.FileNotFoundException thrown if the file cannot be found
     * @throws java.io.IOException thrown if there is an issue with reading the file
     */
    private byte[] getFileBytes(File f) throws IOException{
        InputStream in = new FileInputStream(f);
        //This finds out how long the file is and whether it is small enough to be transfered
        long length = f.length();
        if(length > Integer.MAX_VALUE){
            System.out.println("File to large");
            return null;
        }
        //creates a byte[] of the length of the file
        byte[] bytes = new byte[(int)length];

        //this section reads the file in and stores it in the byte[]
        int offset = 0;
        int numRead = 0;
        while(numRead >= 0){
            numRead = in.read(bytes,offset,bytes.length - offset);
            offset += numRead;
        }

        //if the file is incomplete then this statement will find it and thrown an exception
        if(offset < bytes.length){
            throw new IOException("File Not Completely Read"+ f.getName());
        }
        in.close();

        return bytes;
    }
}
