/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FileDownload.java
 *
 * Created on 30-May-2009, 12:02:08
 */

package intranetchat.display;

import intranetchat.core.FileTransferListener;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Philip White
 */
public class FileDownload extends javax.swing.JDialog implements Observer{
    byte[] file;
    String name;
    /** Creates new form FileDownload */
    public FileDownload(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mainPanel.setPreferredSize(new java.awt.Dimension(250, 100));
        mainPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("File Downloading from :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        mainPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("username");
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        mainPanel.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        mainPanel.add(jProgressBar1, gridBagConstraints);

        jButton1.setText("Save File");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        mainPanel.add(jButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(mainPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void update(Observable o, Object arg) {
        if(o instanceof FileTransferListener){
            FileTransferListener ftl = (FileTransferListener)o;
            jProgressBar1.setMaximum(ftl.getLength());
            jProgressBar1.setValue(ftl.getPosition());

            if(!(ftl.getPosition() < ftl.getLength())){
                jLabel1.setText("File Downloading from :");
                file = ftl.getFileBytes();
                name = ftl.getFileName();

            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

}
