/*
 * PrivateChat.java
 *
 * Created on 01 February 2008, 10:17
 */

package net.intrenetchat;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;

/**
 * Allows two users to communicate without anyone listening
 * @author  Philip White
 */
public class PrivateChat extends javax.swing.JFrame implements Runnable {
    private PrivateArray parent;
    private Encrypter encrypt;
    private Saving save;
    private String cUser;
    private String user;
    private Network net;
    private String conv;

    /** Creates new form PrivateChat
     * @param u computers Username
     * @param us computers unique computer name
     * @param p instance of the privateArray
     */
    public PrivateChat(String u, String us, PrivateArray p) {
        initComponents();
        net = Network.getInstance();
        save = Saving.getInstance();
        encrypt = Encrypter.getInstance();
        parent = p;
        cUser = u;
        user = us;
        conv = "";
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setTitle("Private chat with "+user);
        this.setLocation(save.getX()+100, save.getY()+20);
        this.setFont();
        this.setBackground();
        this.setForground();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Send");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jMenu2.setText("Help");

        jMenuItem3.setText("About");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem3MousePressed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jMenu3.setText("File");

        jMenuItem4.setText("Clear Screen");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem1.setText("Send File");
        jMenu3.add(jMenuItem1);

        jMenuItem5.setText("Exit");
        jMenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Help");

        jMenuItem6.setText("About");
        jMenuItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem3MousePressed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        this.sendMessage();
    }//GEN-LAST:event_jButton1MousePressed

    private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
        this.jTextArea1.setText("");
    }//GEN-LAST:event_jMenuItem1MousePressed

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        this.dispose();
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void jMenuItem3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MousePressed
        About ab = new About(this,true,this.getX()+50,this.getY()+20);
        ab.setVisible(true);
    }//GEN-LAST:event_jMenuItem3MousePressed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden

    }//GEN-LAST:event_formComponentHidden

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(save.getPriChatHist() == 1){
            save.savePrivate(user, conv);
        }        
        parent.disconnect(cUser);
          this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){
            this.sendMessage();
        }
    }//GEN-LAST:event_jTextField1KeyPressed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Gets the computer unique name
     * @return the computers unique name
     */
    public String getCUser(){
        return cUser;
    }
    
    /**
     * Adds a message onto the main display window
     * @param message Incoming message
     */
    public void appendMessage(String name,String message){
        if(message.charAt(0) == '^'){
            message = encrypt.decrypt(message);
        }
        this.conv += "> "+name+message+"\n";
        this.jTextArea1.append("> "+name+message+"\n");
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }
    
    /**
     * Sends a message to the other party in the group and adds it to screen
     */
    public void sendMessage(){
        String message = this.jTextField1.getText();
        if(save.getEnc() == 1){
            message = encrypt.encrypt(message);
        }
        String mes = "~3~"+cUser+"~"+save.getName()+"~"+message+"~";
        net.sendMulticast(mes);
        this.conv += "< "+save.getName()+": "+this.jTextField1.getText()+"\n";
        this.jTextArea1.append("< "+save.getName()+": "+this.jTextField1.getText()+"\n");
        this.jTextField1.setText("");
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());

    }

    /**
     * Method that is run when the thread starts
     */
    public void run() {
        this.setVisible(true);
    }
    
    /**
     * Sets the background color of the windows
     */
    public void setBackground(){
        String color = save.getBack();
        Color c = this.getColor(color);
        this.jTextArea1.setBackground(c);
        this.jTextField1.setBackground(c);
    }
    
    /**
     * Sets the font colour 
     */
    public void setForground(){
        String color = save.getFront();
        Color c = this.getColor(color);
        this.jTextArea1.setForeground(c);
        this.jTextField1.setForeground(c);
    }
    
    /**
     * Sets the font style
     */
    public void setFont(){
        int style = 0;
        Font f = new Font(save.getFont(),style,save.getFontSize());
        this.jTextArea1.setFont(f);
        this.jTextField1.setFont(f);
    }
    
    private Color getColor(String name){
        Color c = null;
        if(name.compareTo("WHITE")==0){
            c = Color.WHITE;
        }else if(name.compareTo("BLACK")==0){
            c = Color.BLACK;
        }else if(name.compareTo("GREEN")==0){
            c = Color.GREEN;
        }else if(name.compareTo("BLUE")==0){
            c = Color.BLUE;
        }else if(name.compareTo("YELLOW")==0){
            c = Color.YELLOW;
        }else if(name.compareTo("RED")==0){
            c = Color.RED;
        }else if(name.compareTo("ORANGE")==0){
            c = Color.ORANGE;
        }
        return c;
    }
}
